### ISSUE TITLE
MVPレビュー依頼

### ISSUE THREAD

**Issue by ryo-mogura** [ryo-mogura/Pantry-Chef-Notifier#104]
MVP リリース用の issue を作成いたしました。
レビューをよろしくお願いいたします。
## 各種情報
サービス名：Pantry-Chef-Notifier（食材管理とレシピ提示アプリ）
サービスURL：https://pantry-chef-notifier.onrender.com
GitHub URL：https://github.com/ryo-mogura/Pantry-Chef-Notifier
## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [ ] ユーザー登録
  - [ ] メール・パスワード
  - [ ] Lineログイン
- [ ] アカウント
  - [ ] プロフィール
- [ ] 食材リスト
  - [ ] 登録
  - [ ] 編集（詳細ページで行う）
  - [ ] 削除
  - [ ] ソート (消費期限順、名前順)
- [ ] Line通知(AM:8:00に通知が来るように設定)
  - [ ] 消費期限が２日以内の食材のリスト
  - [ ] 消費期限が２日以内の食材を使用したレシピ
- [ ] LineBotとの対話機能
  - [ ] 食材リストの取得
  - [ ] 消費期限リストの取得
  - [ ] レシピ検索
## READMEレビュー時から変更した機能
- [ ] LineBotとの対話機能
  - [ ] 食材の登録
## サービスイメージがわかるようなスクリーンショット等
ログイン前トップページ | 食材リストページ
-- | --
[![Image from Gyazo](https://i.gyazo.com/1f6985bfad53db6a529686e89dcc1a94.gif)](https://gyazo.com/1f6985bfad53db6a529686e89dcc1a94) | [![Image from Gyazo](https://i.gyazo.com/abb364ef28956fdee46c6a3f0c28c5b7.gif)](https://gyazo.com/abb364ef28956fdee46c6a3f0c28c5b7)
新規登録ページ |  ログインページ
[![Image from Gyazo](https://i.gyazo.com/d6f8bcfc9d05a47bf22f8d1a8ef07c2f.png)](https://gyazo.com/d6f8bcfc9d05a47bf22f8d1a8ef07c2f) | [![Image from Gyazo](https://i.gyazo.com/66fe30a83d1dc7ef9dd5cfb1c151e733.png)](https://gyazo.com/66fe30a83d1dc7ef9dd5cfb1c151e733) |
パスワード申請ページ | パスワードリセットページ
[![Image from Gyazo](https://i.gyazo.com/97661601ab845269e9a61d8a8e0f1ed2.png)](https://gyazo.com/97661601ab845269e9a61d8a8e0f1ed2) | [![Image from Gyazo](https://i.gyazo.com/a37a867d9486b5a312a35479926c9838.png)](https://gyazo.com/a37a867d9486b5a312a35479926c9838)
食材登録ページ | 食材詳細ページ
[![Image from Gyazo](https://i.gyazo.com/50ed5d695ea3aad27e7edee63747d6cf.png)](https://gyazo.com/50ed5d695ea3aad27e7edee63747d6cf) | [![Image from Gyazo](https://i.gyazo.com/553454b0f7839484f9527d21d5b9ed19.png)](https://gyazo.com/553454b0f7839484f9527d21d5b9ed19)
食材の編集（詳細ページ上）| 食材の削除
[![Image from Gyazo](https://i.gyazo.com/a358b16d92c2f69bd80a662333497890.gif)](https://gyazo.com/a358b16d92c2f69bd80a662333497890) | [![Image from Gyazo](https://i.gyazo.com/edaa1875892bd59cff59ad1f54afa211.gif)](https://gyazo.com/edaa1875892bd59cff59ad1f54afa211)
レシピ検索ページ | マイページ
[![Image from Gyazo](https://i.gyazo.com/4f348ca4689a5c47c835ba401b4bf551.gif)](https://gyazo.com/4f348ca4689a5c47c835ba401b4bf551) | [![Image from Gyazo](https://i.gyazo.com/25d9a1c85e6ff389edd7fc5014196c8e.png)](https://gyazo.com/25d9a1c85e6ff389edd7fc5014196c8e)
### Line上からの操作画面
メニュー画面 | 食材の登録
-- | --
[![Image from Gyazo](https://i.gyazo.com/ed6d8872f50a62dc57dabb7721c9ab35.png)](https://gyazo.com/ed6d8872f50a62dc57dabb7721c9ab35) | [![Image from Gyazo](https://i.gyazo.com/4ffe7607af8f809cc12cf687836021d6.png)](https://gyazo.com/4ffe7607af8f809cc12cf687836021d6)
食材リストの取得 | 消費期限が2日以内の食材の取得
[![Image from Gyazo](https://i.gyazo.com/84beb61d1f884c6ab8a3175f711c7dd3.png)](https://gyazo.com/84beb61d1f884c6ab8a3175f711c7dd3) | [![Image from Gyazo](https://i.gyazo.com/25062e2fec3eff88bde3daae9fecf1a9.png)](https://gyazo.com/25062e2fec3eff88bde3daae9fecf1a9)
レシピ検索 | 入力情報のリセット
[![Image from Gyazo](https://i.gyazo.com/48802a38ff45551edd25e31146753e41.png)](https://gyazo.com/48802a38ff45551edd25e31146753e41) | [![Image from Gyazo](https://i.gyazo.com/d0ab0b93d153a15fc9b64aabb4c73eaa.png)](https://gyazo.com/d0ab0b93d153a15fc9b64aabb4c73eaa)

**Comment by shota-hope** [comment]
提出ありがとうございます。LGTMです！

**Comment by ryo-mogura** [comment]
レビューありがとうございました！！
