### ISSUE TITLE
"issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by ryo-mogura** [ryo-mogura/Pantry-Chef-Notifier#89]
### 概要
リリースまでのissueを作成しました。
実装済みの機能はチェックマークをつけています。
レビューよろしくお願いいたします。
#### MVP
- [x] ユーザー登録
  -  [x] メール・パスワード
  - [x] Lineログイン
- [ ]  アカウント
  -  [ ] プロフィール
- [x] 食材リスト
  - [x] 登録
  - [x]  編集（詳細ページで行う）
  - [x] 削除
  - [x] ソート (消費期限順、名前順)
- [x] Line通知(AM:8:00に通知が来るように設定)
  - [x] 消費期限が２日以内の食材のリスト
  - [x] 消費期限が２日以内の食材を使用したレシピ
- [x] LineBotとの対話機能
  - [x] 食材リストの取得
  - [x] 消費期限リストの取得
  - [x] レシピ検索
#### 本リリース
- [ ] 食材のカテゴリー機能
- [ ] LineBotとの対話機能
  - [ ] 食材の登録
- [ ] 食材画像の共有機能
- [ ] レシピのお気に入り機能
### 必要なページ
- [x] トップページ
- [x] ログインページ
- [x] 新規登録ページ
- [x] 食材一覧ページ
- [x] 食材登録ページ
- [x] 食材詳細ページ
- [x] レシピ検索ページ
- [ ] マイページ 
- [ ] パスワードリセット申請ページ
- [ ] パスワードの再設定ページ

**Comment by Tsuchiya2** [comment]
概ね良いかと思います。LGTMです。

**Comment by ryo-mogura** [comment]
レビューありがとうございました！
